{% set name = "ncvue" %}
{% set version = "4.2" %}
{% set sha256 = "b98a1ac87e541adef7e759c924f7cabd332289faf0315497dde228481f23505e" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ncvue-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - ncvue = ncvue.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=42
    - setuptools_scm >=3.5
  run:
    - python
    - pykdtree
    - numpy
    - matplotlib-base
    - netcdf4
    - cartopy
    - tk  # [linux]

test:
  commands:
    - python -c "import ncvue"  # [not linux]

app:
  entry: python -m ncvue
  icon: ncvue_icon.png
  summary: ncvue - a minimal GUI for a quick view of netcdf files
  type: desk
  own_environment: True

about:
  home: https://github.com/mcuntz/ncvue
  summary: 'A minimal GUI for a quick view of netcdf files'
  dev_url: https://github.com/mcuntz/ncvue
  license: MIT
  license_file: LICENSE
  description: |
    ncvue is a minimal GUI for a quick view of netCDF files. It is aiming to
    be a drop-in replacement for ncview and panoply, being slightly more
    general than ncview targeting only maps but providing animations, zooming
    and panning capabilities unlike panoply. If ncvue is used with maps,
    it supports mostly structured grids, more precisely the grids supported by
    cartopy.
  doc_url: https://mcuntz.github.io/ncvue

extra:
  recipe-maintainers:
    - mcuntz
